events {}

http {
    server {
        listen 80;

        location / {
            proxy_pass http://nodegoat-app:4000;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            gzip on;

            add_header X-Frame-Options SAMEORIGIN;
            add_header X-Content-Type-Options nosniff;

            server_tokens off;
        }
    }
}
